- name: Install required packages
  ansible.builtin.yum:
    name:
      - python3
      - python3-pip
    state: present
  become: yes

- name: Install required packages
  ansible.builtin.yum:
    name:
      - python3
      - python3-pip
    state: present
  become: yes

- name: Create monitoring app directory
  ansible.builtin.file:
    path: /opt/monitor-app
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Copy monitoring Flask app
  ansible.builtin.copy:
    src: monitor-app.py
    dest: /opt/monitor-app/app.py
    mode: '0755'
  become: yes

- name: Copy systemd service unit
  ansible.builtin.template:
    src: monitor-app.service.j2
    dest: /etc/systemd/system/monitor-app.service
  become: yes

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: yes

- name: Enable and start monitor Flask app
  ansible.builtin.systemd:
    name: monitor-app
    enabled: yes
    state: started
  become: yes

- name: Install Nginx
  dnf:
    name: nginx
    state: present
    update_cache: yes
  become: true

- name: Configure Nginx upstream
  become: true
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Restart Nginx
  become: true
  service:
    name: nginx
    state: restarted
