- name: Install Nginx
  dnf:
    name: nginx
    state: present
    update_cache: yes
  become: true

- name: Configure Nginx upstream
  become: true
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Restart Nginx
  become: true
  service:
    name: nginx
    state: restarted
